# Site settings
title:          Chiseung Ahn's Github
description:    "Trying to keep records and learn"
url:            https://chiseungahn96.github.io

# Author
author:
  name:         Chiseung Ahn
  email:        acs1113@naver.com
  url:          https://github.com/chiseungahn96

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: acs1113@naver.com
  github: https://github.com/chiseungahn96
  linkedin: https://www.linkedin.com/in/chiseung-ahn-b514b1192/
